# Skaffold for the full stack (eventually). Run:
# skaffold dev 
# If you quite skaffold, the directory PVC are not deleted. You need to manually delete:
# kubectl delete pvc --all
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: gcr.io/engineering-devops/sk-ig
    context: ig
  - image: gcr.io/engineering-devops/sk-amster
    context: amster
  - image: gcr.io/engineering-devops/sk-am
    context: am
  - image: gcr.io/engineering-devops/sk-idm
    context: idm
  tagPolicy:
    sha256: {}
deploy:
  helm:
    flags:
      install: [ '-f', 'helm-common.yaml']
      upgrade: [ '-f', 'helm-common.yaml']
    releases:
    - name: "{{.HELM_PREFIX}}frconfig"
      chartPath: ../helm/frconfig
    - name: "{{.HELM_PREFIX}}idrepo"
      chartPath: ../helm/ds
      setValues:
        instance: idrepo
    - name: "{{.HELM_PREFIX}}sk-am"
      chartPath: ../helm/am
      values:
        image: gcr.io/engineering-devops/sk-am
    - name: "{{.HELM_PREFIX}}sk-amster"
      chartPath: ../helm/amster
      values:
        image: gcr.io/engineering-devops/sk-amster
    # - name: "{{.HELM_PREFIX}}sk-idm
    #   chartPath: ../helm/idm
    #   values:
    #     image: gcr.io/engineering-devops/sk-idm
    - name: "{{.HELM_PREFIX}}ig"
      chartPath: ../helm/ig
      values:
        image: gcr.io/engineering-devops/sk-ig
profiles:
# Profile used to initialize the idrepo ds instance with the skeleton AM config. AM file based config
# needs this to bootstrap. This limitation should be removed shortly.
# Run this with skaffold run -p init 
- name: init
  deploy:
    helm:
      flags:
        install: ['-f', 'helm-common.yaml']
      releases:
      - name: "{{.HELM_PREFIX}}idrepo"
        chartPath: ../helm/ds
        setValues:
          instance: idrepo
      - name: "{{.HELM_PREFIX}}sk-am"
        chartPath: ../helm/am
        values:
          image: gcr.io/engineering-devops/sk-am
        setValues:
          catalinaOpts: "-server -Dcom.sun.identity.sm.sms_object_filebased_enabled=true"
      - name: "{{.HELM_PREFIX}}sk-amster"
        chartPath: ../helm/amster
        values:
          image: gcr.io/engineering-devops/sk-amster
# Deploy to test namespace using git commit tags instead of sha256
- name: test
  build:
    tagPolicy:
      gitCommit: {}
# Additional profiles can be added here for the various t-shirt sizes.
- name: large
  deploy:
    helm:
      flags:
        install: ['-f', 'helm-common.yaml']
# A "dev" instance where the data in ds is ephemeral - goes away after each install.  
- name: dev
  deploy:
    helm:
      flags:
        install: [ '-f', 'helm-common.yaml']
        upgrade: [ '-f', 'helm-common.yaml']
      releases:
      - name: "{{.HELM_PREFIX}}frconfig"
        chartPath: ../helm/frconfig
      - name: "{{.HELM_PREFIX}}idrepo"
        chartPath: ../helm/ds
        setValues:
          instance: idrepo
          persistence: false
      - name: "{{.HELM_PREFIX}}sk-am"
        chartPath: ../helm/am
        values:
          image: gcr.io/engineering-devops/sk-am
        setValues:
          catalinaOpts: "-server -Dcom.sun.identity.sm.sms_object_filebased_enabled=true"
      - name: "{{.HELM_PREFIX}}sk-amster"
        chartPath: ../helm/amster
        values:
          image: gcr.io/engineering-devops/sk-amster
      - name: "{{.HELM_PREFIX}}sk-idm"
        chartPath: ../helm/idm
        values:
          image: gcr.io/engineering-devops/sk-idm
      - name: "{{.HELM_PREFIX}}ig"
        chartPath: ../helm/ig
        values:
          image: gcr.io/engineering-devops/sk-ig